# Generated by Django 2.2.7 on 2019-12-06 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('downvotes', models.ManyToManyField(blank=True, related_name='answer_downvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_image/')),
                ('description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True)),
                ('snippet', models.ImageField(blank=True, null=True, upload_to='question/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='dashboardapp.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverimage', models.ImageField(blank=True, default='default.jpg', upload_to='profile/')),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='profile/')),
                ('bio', models.CharField(blank=True, default='bio', max_length=30)),
                ('email', models.EmailField(blank=True, default='moringa@gmail.com', max_length=254)),
                ('facebook_page', models.URLField(blank=True, default='https://www.youtube.com/watch?v=CQ90L5jfldw&t=417s')),
                ('twitter_link', models.URLField(blank=True, default='https://www.youtube.com/watch?v=CQ90L5jfldw&t=417s')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Approved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve', models.BooleanField()),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboardapp.Answer')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboardapp.Question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardapp.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='answer_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
