# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-14 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approved',
            old_name='user',
            new_name='name',
        ),
    ]
