# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-14 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0002_auto_20191114_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='name',
        ),
    ]
