# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-18 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0003_auto_20191118_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='category_name',
        ),
    ]
