# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-14 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0003_auto_20191114_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='image',
            new_name='snippet',
        ),
    ]
