# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-21 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0005_auto_20191121_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='dashboardapp.Category'),
        ),
    ]
