# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-21 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0006_auto_20191121_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, upload_to='question/'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
