# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-22 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0009_auto_20191121_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='snippet',
            field=models.ImageField(null=True, upload_to='question/'),
        ),
    ]
