# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-02 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0012_auto_20191202_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upvote',
            old_name='name',
            new_name='user_name',
        ),
    ]
