# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-02 12:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboardapp', '0013_auto_20191202_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='likes',
            new_name='votes',
        ),
        migrations.AddField(
            model_name='uservotes',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_votes', to='dashboardapp.Answer'),
        ),
        migrations.AddField(
            model_name='uservotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='uservotes',
            unique_together=set([('user', 'answer', 'vote_type')]),
        ),
    ]
