# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-02 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0014_auto_20191202_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='votes',
            new_name='downvotes',
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
