# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-04 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0016_auto_20191203_0732'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservotes',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='uservotes',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='uservotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='downvotes',
        ),
        migrations.AddField(
            model_name='answer',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UserVotes',
        ),
    ]
